name: KICS IaC Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kics_scan:
    name: Run KICS Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run KICS scan
        uses: Checkmarx/kics-github-action@v1.7
        with:
          path: .
          fail_on: high  # Fail the action on high severity issues
          output_path: kics_results
          output_formats: 'sarif,html,json'
      
      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: kics_results/results.sarif

      - name: Archive KICS scan results
        uses: actions/upload-artifact@v4
        with:
          name: kics-results
          path: kics_results
