  name: Vorpal Code Review

  on: [pull_request]

  jobs:
    vorpal-reviewdog:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Run Vorpal with Reviewdog
          uses: Checkmarx/vorpal-reviewdog-github-action@main
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            source_path: '.'
            folders_to_ignore: 'tests,docs'
            level: 'warning'
